import os
import subprocess

def solve_with_pddl(env, start_state):
    # 1. Generate PDDL files
    domain_file = "domain.pddl" # (Static, written once)
    problem_file = generate_pddl(env, start_state)

    # 2. Call the Planner (Example using Fast Downward)
    # Command: fast-downward domain.pddl problem.pddl --search "astar(lmcut())"
    cmd = [
        "./fast-downward.py", # Path to your solver
        domain_file,
        problem_file,
        "--search", "astar(lmcut())" # Optimal configuration
    ]

    print(f"Running PDDL planner...")
    result = subprocess.run(cmd, capture_output=True, text=True)

    # 3. Parse Output (Task 2.2 Requirement)
    if "Solution found" in result.stdout:
        # Parse the 'sas_plan' file generated by Fast Downward
        with open("sas_plan", "r") as f:
            plan = f.read()
        return plan
    else:
        print("No solution found by planner.")
        return None